#!/bin/sh -e
# Prints the list of installed packages
# [list_of_packages]

MANIFEST="$(pkgmanager get-metadata-install-dir)"
[ $# -ne 0 ] || set -- "$PWD"
for pkg do
    cat "$MANIFEST/$(basename "$pkg")/manifest"
done
