#!/bin/sh -e
# Fetches any updates from repositories and builds/installs updates
# Takes no arguments

pkgmanager fetch
# shellcheck disable=2046
set -- $(pkgmanager outdated)

[ $# -eq 0 ] && exit 0

for pkg do
    pkgmanager build "$pkg"
    pkgmanager install "$pkg"
done
