#!/bin/sh -e
# List all packages without a repository
# Takes no arguments

pkgmanager list | while read -r pkg _; do
    if ! PKGMANAGER_HIDE_INSTALL_DIR=1 pkgmanager find "$pkg" >/dev/null; then
        echo "$pkg"
    fi
done
