#!/bin/sh -e
# Show diff between top 2 sources of a given pkg
# [pkg]
# Use PKGMANAGER_FORCE to diff multiple repos

pkg="$1"
use_local=0
if [ -z "$pkg" ] || [ "$pkg" = "." ]; then
    pkg=$(basename "$PWD")
    use_local=1
    cd ..
elif [ -d "$pkg" ]; then
    use_local=1
elif ! pkgmanager s "$pkg" >> /dev/null; then
    echo "Invalid pgk $pkg"
    exit 1
fi

pkgmanager s "$pkg" |  {
    if [ $use_local -eq 0 ]; then
        read -r us
    else
        us=$pkg
    fi
    while read -r them ; do
        test "$them" -ef "$us" && continue
        diff -u "$them" "$us"
        [ "${PKGMANAGER_FORCE:-0}" -eq 1 ] || break
    done
}
