#!/bin/sh -e
# Swaps Replace path with pkg's implementation
# pkg path

remove_existing_file() {
    path=$1
    if [ -e "$PKGMAN_ROOT/$path" ]; then
        owner=$(pkgmanager owns "$path") || return 0
        METADATA=$(pkgmanager get-metadata-install-dir "$owner")
        DIR="$METADATA/conflicts"
        CONFLICT_PATH="$DIR/$path"

        mkdir -p "$(dirname "$CONFLICT_PATH")"
        cp -Pf "$PKGMAN_ROOT/$path" "$CONFLICT_PATH"
        echo "${CONFLICT_PATH#"$PKGMAN_ROOT"}" | pkgmanager update-manifest "$METADATA/manifest" - "$path"
    fi
}

restore_conflict() {
    pkg=$1
    path=$2
    if [ -n "$pkg" ]; then
        METADATA=$(pkgmanager get-metadata-install-dir "$pkg")
        DIR="$METADATA/conflicts"
        CONFLICT_PATH="$DIR/$path"
        mv "$CONFLICT_PATH" "$PKGMAN_ROOT/$path"
        echo "$path" | pkgmanager update-manifest "$METADATA/manifest" - "${CONFLICT_PATH#"$PKGMAN_ROOT"}"
    else
        rm "$PKGMAN_ROOT/$path"
    fi
}

remove_existing_file "$2"
restore_conflict "$1" "$2"
