#!/bin/sh -e
# Fetches any updates from repositories and builds/installs updates
# [git]
# If git is run, then all git packages (and only them) will be rebuilt and installed

pkgmanager fetch

BUILD=0
# shellcheck disable=2046
if [ "$1" = "git" ]; then
    BUILD=1
    set -- $(pkgmanager list | grep "\sgit\s")
else
    set -- $(pkgmanager outdated)
fi

[ $# -eq 0 ] && exit 0

echo "Updating $*... continue Y/n"
if [ "${PKGMAN_FORCE:-0}" -eq 0 ]; then
    read -r response

    if [ "$response" != y ] && [ "$response" != Y ]; then
        exit 1
    fi
fi

for pkg do
    [ "$BUILD" -eq 0 ] || pkgmanager build "$pkg"
    pkgmanager install "$pkg"
done
