#!/bin/sh -e
# Fetches any updates from repositories and builds/installs updates
# [git]
# If git is run, then all git packages (and only them) will be rebuilt and installed

pkgmanager fetch

# shellcheck disable=2046
set -- $(pkgmanager outdated "$1")

[ $# -eq 0 ] && exit 0

echo "Updating $*... continue Y/n"
if [ "${PKGMAN_FORCE:-0}" -eq 0 ]; then
    read -r response

    if [ "$response" != y ] && [ "$response" != Y ]; then
        exit 1
    fi
fi

for pkg do
    pkgmanager install "$pkg" || [ "${PKGMAN_FORCE:-0}" -eq 1 ]
done
