#!/bin/sh -e
# Creates a new skeleton package
# name [version [sources]]

name=$1
version=${2:-1}
[ ! -e "$name" ] || die "Directory already exists"
mkdir "$name"
echo "$version 1"   > "$name/version"
echo "#!/bin/sh -e" > "$name/build"
chmod +x "$name/build"

if [ $# -gt 2 ]; then
    shift 2
    for source do
        echo "$source"     >> "$name/sources"
    done
fi
