#!/bin/sh -e
# Determine which package owns a given file
# path1 [path2 ... pathN]

METADATA=$(pkgmanager get-metadata-install-dir)
pkg_owns() {
    filepath=$1
}

for filepath do
    manifest=$(grep -slFx "$filepath" "$METADATA/"*/manifest | { read -r m; echo "$m"; })
    [ -n "$manifest" ] && basename "$(dirname "$manifest")"
done
