#!/bin/sh -e
# Shows the active maintainer for a package
# The maintainer is the last person to modify version

for pkg ; do
    path=$(pkgmanager find "$pkg" | cut -f1)
    cd "$path" && git blame --line-porcelain version | sed -n 's/^author\(-mail\| \)//p'
done

