#!/bin/sh -e
# Helper to atomically update a manifest file
# manifest_file file_to_append [entry_to_remove]

[ -e "$1" ]
[ -n "$_PKGMAN_HAS_METADATA_LOCK" ] || _PKGMAN_HAS_METADATA_LOCK=1 exec flock -n -s "$(pkgmanager get-metadata-install-dir)/.lock" "$0" "$@"
[ -n "$MANIFEST_LOCK" ] || MANIFEST_LOCK=1 exec flock -n "$1" "$0" "$@"

TEMP="${TMPDIR:-/tmp}/$$/"
trap 'rmdir $TEMP' EXIT
temp_manifest="$TEMP/manifest"
mkdir -p "$TEMP"
sort "$1" "$2" > "$temp_manifest"
mv "$temp_manifest" "$1"

[ -z "$3" ] || sed -i "s:^$3\$::; /^\$/d" "$1"
